### ISSUE TITLE
freeze block all node

### ISSUE THREAD

**Issue by meltaus** [branciard/DAppNodePackage-polkadot#3]
![screenshot_20190209_112111](https://user-images.githubusercontent.com/13775964/52516398-03de6d00-2c5d-11e9-95d5-449950af6ca9.png)
![screenshot_20190209_112327](https://user-images.githubusercontent.com/13775964/52516406-22446880-2c5d-11e9-94f8-f6fde5cfc54b.png)
My version 0.3.12

**Comment by branciard** [comment]
It may have freeze sometime. Polkadot is in beta and testnet. You can try the latest release that is  more stable : https://github.com/branciard/DAppNodePackage-polkadot-alexander/releases/tag/v0.0.7
